from pathlib import Path
p=Path('apps/backend/prisma/schema.prisma')
s=p.read_text()
if 'model QaImprovementAction {' in s:
    raise SystemExit(0)

s=s.replace('''enum QaAnalysisReviewDecision {\n  Confirmed\n  Rejected\n  NeedsMoreEvidence\n}\n''','''enum QaAnalysisReviewDecision {\n  Confirmed\n  Rejected\n  NeedsMoreEvidence\n}\n\nenum QaImprovementActionStatus {\n  Open\n  InProgress\n  Completed\n  Cancelled\n}\n''',1)
s=s.replace('''  qaAnalysisReviews       QaEvidenceAnalysisReview[] @relation("QaAnalysisReviewer")\n''','''  qaAnalysisReviews       QaEvidenceAnalysisReview[] @relation("QaAnalysisReviewer")\n  qaImprovementActionsOwned QaImprovementAction[]    @relation("QaActionOwner")\n''',1)
s=s.replace('''  qaAnalysisReviews QaEvidenceAnalysisReview[]\n''','''  qaAnalysisReviews QaEvidenceAnalysisReview[]\n  qaImprovementActions QaImprovementAction[]\n''',1)
s=s.replace('''  analyses     QaEvidenceAnalysis[]\n\n  @@unique([criterionId, code])''','''  analyses     QaEvidenceAnalysis[]\n  improvementActions QaImprovementAction[]\n\n  @@unique([criterionId, code])''',1)
s=s.replace('''  analyses    QaEvidenceAnalysis[]\n\n  @@index([programmeId, status])''','''  analyses    QaEvidenceAnalysis[]\n  improvementActions QaImprovementAction[]\n\n  @@index([programmeId, status])''',1)
s=s.replace('''  reviews         QaEvidenceAnalysisReview[]\n\n  @@index([programmeId, cycleId, createdAt])''','''  reviews         QaEvidenceAnalysisReview[]\n  improvementActions QaImprovementAction[]\n\n  @@index([programmeId, cycleId, createdAt])''',1)
s=s.replace('''  createdAt   DateTime                 @default(now())\n\n  @@index([programmeId, createdAt])''','''  createdAt   DateTime                 @default(now())\n  improvementActions QaImprovementAction[]\n\n  @@index([programmeId, createdAt])''',1)
# Clean misplaced comment introduced while inserting the review model in #191.
s=s.replace('''/// Immutable snapshot of a source used by one analysis run. Structured entity\n/// identity is retained even if source content changes later; qaEvidenceId is an\n/// optional convenience FK for manually attached QA evidence.\n/// Append-only human validation of one exact evidence-analysis version.\nmodel QaEvidenceAnalysisReview''','''/// Append-only human validation of one exact evidence-analysis version.\nmodel QaEvidenceAnalysisReview''',1)
s=s.replace('''model QaEvidenceAnalysisSource {\n''','''/// Immutable snapshot of a source used by one analysis run. Structured entity\n/// identity is retained even if source content changes later; qaEvidenceId is an\n/// optional convenience FK for manually attached QA evidence.\nmodel QaEvidenceAnalysisSource {\n''',1)

anchor='''model QaEvidenceAnalysisSource {\n'''
model='''/// Operational PDCA/CQI action created from a human-validated evidence finding.\n/// The originating analysis/review remain immutable; the action lifecycle is mutable.\nmodel QaImprovementAction {\n  id                  String                    @id @default(uuid())\n  programmeId         String\n  programme           Programme                 @relation(fields: [programmeId], references: [id], onDelete: Restrict)\n  cycleId             String\n  cycle               QaAssessmentCycle         @relation(fields: [cycleId], references: [id], onDelete: Cascade)\n  requirementId       String\n  requirement         QaRequirement             @relation(fields: [requirementId], references: [id], onDelete: Restrict)\n  analysisId          String\n  analysis            QaEvidenceAnalysis        @relation(fields: [analysisId], references: [id], onDelete: Cascade)\n  reviewId            String\n  review              QaEvidenceAnalysisReview  @relation(fields: [reviewId], references: [id], onDelete: Cascade)\n  ownerId             String?\n  owner               User?                     @relation("QaActionOwner", fields: [ownerId], references: [id], onDelete: SetNull)\n  plannedAction       String\n  indicator           String\n  dueDate             DateTime?\n  status              QaImprovementActionStatus @default(Open)\n  result              String                    @default(\"\")\n  effectivenessReview String                    @default(\"\")\n  completedAt         DateTime?\n  carriedFromActionId String?\n  carriedFrom         QaImprovementAction?       @relation("QaActionCarryForward", fields: [carriedFromActionId], references: [id], onDelete: SetNull)\n  carriedTo           QaImprovementAction[]      @relation("QaActionCarryForward")\n  createdAt           DateTime                  @default(now())\n  updatedAt           DateTime                  @updatedAt\n\n  @@index([programmeId, status, dueDate])\n  @@index([cycleId, status])\n  @@index([requirementId])\n  @@index([analysisId])\n  @@index([reviewId])\n  @@index([ownerId])\n  @@index([carriedFromActionId])\n}\n\n'''
if anchor not in s: raise SystemExit('source model anchor not found')
s=s.replace(anchor,model+anchor,1)
p.write_text(s)
