"use client";

import { useCallback, useState } from "react";
import { BookOpen, CalendarDays, CheckCircle2, Download, ExternalLink, FileCheck2, MessageSquareText, Target, UserRound } from "lucide-react";
import type { CourseFeedbackInput, PortalCourseDetail } from "@dse-pms/shared-types";
import { Button, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, Progress, Tabs, TabsContent, TabsList, TabsTrigger } from "@dse-pms/ui";
import { assessmentDeadline, meetingLabel, studentPortalApi } from "@/lib/student-portal";
import { PortalError, PortalLoading, usePortalData } from "../../portal-state";

export function PortalCourse({ offeringId }: { offeringId: string }) {
  const load = useCallback(() => studentPortalApi.course(offeringId), [offeringId]);
  const { data, loading, error, setData } = usePortalData(load);
  const [feedbackOpen, setFeedbackOpen] = useState(false);
  if (loading) return <PortalLoading />;
  if (error || !data) return <PortalError message={error ?? "Could not load course"} />;
  return <div className="mx-auto max-w-7xl space-y-5">
    <section className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{data.code}</span><span className="rounded-lg bg-muted px-3 py-1 text-xs">Section {data.sectionCode}</span><span className="rounded-lg bg-muted px-3 py-1 text-xs">{data.term}</span></div><h2 className="mt-3 text-2xl font-bold">{data.title}</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{data.description || "No course description has been published."}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setFeedbackOpen(true)} disabled={data.feedbackSubmitted}><MessageSquareText />{data.feedbackSubmitted ? "Feedback submitted" : "Course feedback"}</Button><Button onClick={() => downloadCourseDocument(data)} disabled={!data.specAvailable}><Download />Download approved document</Button></div></div>
      <div className="mt-5 grid gap-3 border-t border-border pt-5 sm:grid-cols-2 lg:grid-cols-4"><Info icon={UserRound} label="Lecturer" value={data.lecturer?.name ?? "TBA"} /><Info icon={CalendarDays} label="Schedule" value={data.meetings[0] ? meetingLabel(data.meetings[0]) : "TBA"} /><Info icon={BookOpen} label="Credits" value={data.credits ? `${data.credits} credits` : "TBA"} /><Info icon={Target} label="CLO achievement" value={data.overallAchievement === null ? "No evidence yet" : `${data.overallAchievement}%`} /></div>
    </section>
    {!data.specAvailable ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300">The course specification is still under review. Learning details will appear after approval.</div> : <Tabs defaultValue="overview"><TabsList className="max-w-full overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="learning">Learning</TabsTrigger><TabsTrigger value="assessments">Assessments</TabsTrigger><TabsTrigger value="results">Results</TabsTrigger><TabsTrigger value="resources">Resources</TabsTrigger></TabsList>
      <TabsContent value="overview" className="mt-4 space-y-4"><Card title="Class schedule">{data.meetings.length ? <div className="grid gap-3 sm:grid-cols-2">{data.meetings.map((meeting) => <div key={meeting.id} className="rounded-xl bg-muted/50 p-4"><p className="font-medium">{meeting.activityType}</p><p className="mt-1 text-sm text-muted-foreground">{meetingLabel(meeting)}</p><p className="text-sm text-muted-foreground">{meeting.room || "Room TBA"}</p></div>)}</div> : <Muted>No schedule has been published.</Muted>}</Card><Card title="Teaching team"><p className="font-medium">{data.lecturer?.name ?? "Primary lecturer TBA"}</p><p className="text-sm text-muted-foreground">{data.lecturer?.email}</p>{data.coLecturers.length ? <p className="mt-3 text-sm">Co-lecturers: {data.coLecturers.map((item) => item.name).join(", ")}</p> : null}</Card></TabsContent>
      <TabsContent value="learning" className="mt-4 space-y-4"><Card title="Course learning outcomes"><div className="grid gap-3 md:grid-cols-2">{data.clos.map((clo) => <div key={clo.code} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><span className="font-semibold text-primary">{clo.code}</span><span className="text-xs text-muted-foreground">{clo.level}</span></div><p className="mt-2 text-sm">{clo.description}</p><p className="mt-2 text-xs text-muted-foreground">Supports {clo.mappedPlos.join(", ") || "PLO mapping pending"}</p></div>)}</div></Card><Card title="Weekly topics"><div className="space-y-3">{data.weeks.map((week) => <div key={week.id} className="flex gap-4 rounded-xl bg-muted/40 p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-semibold text-primary-foreground">{week.week}</span><div><p className="font-medium">{week.topic || "Topic to be announced"}</p>{week.learningOutcomes.length ? <p className="mt-1 text-sm text-muted-foreground">{week.learningOutcomes.join(" · ")}</p> : null}<div className="mt-2 flex flex-wrap gap-1">{week.cloCodes.map((code) => <span key={code} className="rounded bg-primary/10 px-2 py-0.5 text-[11px] text-primary">{code}</span>)}</div></div></div>)}</div></Card></TabsContent>
      <TabsContent value="assessments" className="mt-4"><Card title="Assessment plan"><div className="space-y-3">{data.assessments.map((item) => <div key={item.id} className="rounded-xl border border-border p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><div className="flex flex-wrap gap-2"><span className="text-xs font-semibold uppercase text-primary">{item.type}</span><span className="text-xs capitalize text-muted-foreground">{item.mode}</span></div><h4 className="mt-1 font-semibold">{item.name}</h4></div><div className="text-sm sm:text-right"><p className="font-semibold">{item.weight === null ? "Weight TBA" : `${item.weight}%`}</p><p className="text-muted-foreground">{assessmentDeadline(item.dueAt,item.dueWeek)}</p></div></div>{item.description ? <p className="mt-3 text-sm text-muted-foreground">{item.description}</p> : null}<div className="mt-3 flex flex-wrap gap-1">{item.cloCodes.map((code) => <span key={code} className="rounded bg-muted px-2 py-1 text-xs">{code}</span>)}</div>{item.rubricName ? <p className="mt-3 text-sm text-muted-foreground">Rubric: <span className="font-medium text-foreground">{item.rubricName}</span></p> : null}</div>)}</div></Card></TabsContent>
      <TabsContent value="results" className="mt-4 space-y-4"><Card title="CLO achievement"><div className="grid gap-3 md:grid-cols-2">{data.achievements.map((item) => <div key={item.code} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><span className="font-semibold">{item.code}</span><span className="text-sm font-semibold">{item.percentage === null ? "—" : `${item.percentage}%`}</span></div><Progress className="mt-3" value={item.percentage ?? 0} /><p className="mt-2 text-xs text-muted-foreground">{item.evidenceCount ? `${item.evidenceCount} published assessment${item.evidenceCount === 1 ? "" : "s"}` : "Not enough assessment evidence"}</p></div>)}</div></Card><Card title="Published results"><div className="space-y-2">{data.assessments.filter((item) => item.result).map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-muted/40 p-4"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.result?.feedback || "No written feedback"}</p></div><p className="text-lg font-bold">{item.result?.score}/{item.result?.maxScore}</p></div>)}{!data.assessments.some((item) => item.result) ? <Muted>No results have been published.</Muted> : null}</div></Card></TabsContent>
      <TabsContent value="resources" className="mt-4"><Card title="Learning resources"><div className="grid gap-3 md:grid-cols-2">{data.resources.map((item) => <a key={item.id} href={item.url || undefined} target="_blank" rel="noreferrer" className="rounded-xl border border-border p-4 transition hover:border-primary/40"><div className="flex items-start justify-between"><FileCheck2 className="h-5 w-5 text-primary" />{item.url ? <ExternalLink className="h-4 w-4 text-muted-foreground" /> : null}</div><p className="mt-3 font-medium">{item.title || item.resourceType}</p><p className="mt-1 text-xs text-muted-foreground">{item.resourceType}{item.notes ? ` · ${item.notes}` : ""}</p></a>)}</div>{!data.resources.length ? <Muted>No learning resources have been published.</Muted> : null}</Card></TabsContent>
    </Tabs>}
    <FeedbackDialog open={feedbackOpen} onOpenChange={setFeedbackOpen} offeringId={offeringId} onSubmitted={() => setData({ ...data, feedbackSubmitted: true })} />
  </div>;
}

function Info({ icon: Icon, label, value }: { icon: typeof BookOpen; label: string; value: string }) { return <div className="flex items-center gap-3"><span className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="h-4 w-4" /></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm font-medium">{value}</p></div></div>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5"><h3 className="mb-4 text-base font-semibold">{title}</h3>{children}</section>; }
function Muted({ children }: { children: React.ReactNode }) { return <p className="text-sm text-muted-foreground">{children}</p>; }

function FeedbackDialog({ open, onOpenChange, offeringId, onSubmitted }: { open: boolean; onOpenChange: (open:boolean)=>void; offeringId:string; onSubmitted:()=>void }) {
  const [values,setValues]=useState<CourseFeedbackInput>({overallRating:5,teachingClarityRating:5,assessmentClarityRating:5,workload:"appropriate",positiveComment:"",improvementComment:""}); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError(null);try{await studentPortalApi.submitFeedback(offeringId,values);onSubmitted();onOpenChange(false);}catch(reason){setError(reason instanceof Error?reason.message:"Could not submit feedback");}finally{setSaving(false);}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Anonymous course feedback</DialogTitle><DialogDescription>Your identity is not stored with this response. One response is allowed per course section.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}><Rating label="Overall experience" value={values.overallRating} onChange={(value)=>setValues({...values,overallRating:value})}/><Rating label="Teaching clarity" value={values.teachingClarityRating} onChange={(value)=>setValues({...values,teachingClarityRating:value})}/><Rating label="Assessment clarity" value={values.assessmentClarityRating} onChange={(value)=>setValues({...values,assessmentClarityRating:value})}/><label className="block text-sm font-medium">Workload<select className="mt-1 w-full rounded-md border border-input bg-background p-2" value={values.workload} onChange={(e)=>setValues({...values,workload:e.target.value as CourseFeedbackInput["workload"]})}><option value="light">Light</option><option value="appropriate">Appropriate</option><option value="heavy">Heavy</option></select></label><label className="block text-sm font-medium">What helped your learning?<textarea className="mt-1 min-h-20 w-full rounded-md border border-input bg-background p-2" value={values.positiveComment} onChange={(e)=>setValues({...values,positiveComment:e.target.value})}/></label><label className="block text-sm font-medium">What should improve?<textarea className="mt-1 min-h-20 w-full rounded-md border border-input bg-background p-2" value={values.improvementComment} onChange={(e)=>setValues({...values,improvementComment:e.target.value})}/></label>{error?<p className="text-sm text-status-live">{error}</p>:null}<Button className="w-full" disabled={saving}>{saving?"Submitting…":"Submit anonymous feedback"}</Button></form></DialogContent></Dialog>;
}
function Rating({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <div><p className="text-sm font-medium">{label}</p><div className="mt-1 flex gap-2">{[1,2,3,4,5].map((rating)=><button type="button" key={rating} onClick={()=>onChange(rating)} className={`flex h-9 w-9 items-center justify-center rounded-full border text-sm font-semibold ${rating===value?"border-primary bg-primary text-primary-foreground":"border-border hover:border-primary"}`}>{rating}</button>)}</div></div>;}

function escapeHtml(value:string){return value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]!);}
function downloadCourseDocument(course:PortalCourseDetail){const section=(title:string,content:string)=>`<section><h2>${escapeHtml(title)}</h2>${content}</section>`;const html=`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(course.code)} Course Specification</title><style>body{font:15px/1.55 Arial,sans-serif;max-width:900px;margin:40px auto;padding:0 24px;color:#18212f}header{border-bottom:3px solid #185a9d;padding-bottom:16px}h1{margin:0}h2{margin-top:32px;color:#185a9d}article{border:1px solid #d9e0e7;border-radius:10px;padding:14px;margin:10px 0}.meta{color:#667085}ul{padding-left:20px}@media print{body{margin:0;max-width:none}}</style></head><body><header><p class="meta">Approved course specification · ${escapeHtml(course.term)} · Section ${escapeHtml(course.sectionCode)}</p><h1>${escapeHtml(course.code)} — ${escapeHtml(course.title)}</h1><p>${escapeHtml(course.description??"")}</p></header>${section("Course learning outcomes",course.clos.map(item=>`<article><strong>${escapeHtml(item.code)}</strong> ${escapeHtml(item.description)}<div class="meta">${escapeHtml(item.mappedPlos.join(", "))}</div></article>`).join(""))}${section("Weekly plan",course.weeks.map(item=>`<article><strong>Week ${item.week}: ${escapeHtml(item.topic)}</strong><div class="meta">${escapeHtml(item.cloCodes.join(", "))}</div></article>`).join(""))}${section("Assessment plan",course.assessments.map(item=>`<article><strong>${escapeHtml(item.name)}</strong> — ${item.weight??"TBA"}%<div class="meta">${escapeHtml(assessmentDeadline(item.dueAt,item.dueWeek))}</div><p>${escapeHtml(item.description)}</p>${item.rubricName?`<h3>Rubric</h3><p>${escapeHtml(item.rubricName)}</p>`:""}</article>`).join(""))}${section("Learning resources",`<ul>${course.resources.map(item=>`<li>${escapeHtml(item.title||item.resourceType)}${item.url?` — <a href="${escapeHtml(item.url)}">${escapeHtml(item.url)}</a>`:""}</li>`).join("")}</ul>`)}<footer><p class="meta">Downloaded from DSE Program Management System</p></footer></body></html>`;const blob=new Blob([html],{type:"text/html;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${course.code}-approved-course-specification.html`;anchor.click();URL.revokeObjectURL(url);}
