ALTER TABLE "CourseSpecResource"
  ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'OTHER',
  ADD COLUMN "authors" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "publisher" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "year" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "isbn" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "basedOn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "CourseSpecResource" ENABLE ROW LEVEL SECURITY;
