"""One-shot source patch for #1121; executed only on the draft PR branch and removed in its own commit."""
from pathlib import Path


def replace(path: str, old: str, new: str) -> None:
    file = Path(path)
    contents = file.read_text(encoding="utf-8")
    count = contents.count(old)
    if count != 1:
        raise RuntimeError(f"Expected exactly one patch anchor in {path}, found {count}: {old[:100]!r}")
    file.write_text(contents.replace(old, new, 1), encoding="utf-8")


shared = "packages/shared-types/src/attendance.ts"
replace(shared, 'export const SaveAttendanceInput = z.object({\n  records:', 'export const SaveAttendanceInput = z.object({\n  /** Optimistic concurrency precondition; null means no saved session exists yet. */\n  expectedUpdatedAt: z.string().datetime({ offset: true }).nullable().optional(),\n  records:')

frontend = "apps/frontend/app/(shell)/attendance/attendance-client.tsx"
replace(frontend, '    setSaving(true);\n    setMutationError(null);\n    setSavedMessage(null);\n    try {\n      const saved = await offeringsApi.saveAttendance', '    // A server refresh may have arrived while local marks remained dirty. Never\n    // submit the old register against a newer authoritative session.\n    const currentSession = queryClient.getQueryData<AttendanceSessionView>(sessionKey);\n    if (restoredContextRef.current !== attendanceContext ||\n        !currentSession || currentSession.updatedAt !== baselineVersionRef.current) {\n      setMutationError("Attendance changed on the server or is still loading. Your unsaved marks remain on this device. Review the latest register before saving.");\n      return false;\n    }\n    setSaving(true);\n    setMutationError(null);\n    setSavedMessage(null);\n    try {\n      const saved = await offeringsApi.saveAttendance')
replace(frontend, '        records: toSaveAttendanceRecords(records),\n      });', '        records: toSaveAttendanceRecords(records),\n        expectedUpdatedAt: baselineVersionRef.current,\n      });')
replace(frontend, '      setMutationError(err instanceof ApiError ? err.message : "Failed to save attendance");', '      setMutationError(err instanceof ApiError && err.status === 409\n        ? "Attendance was saved by someone else while you were editing. Your unsaved marks are preserved. Review the latest register before attempting another save."\n        : err instanceof ApiError ? err.message : "Failed to save attendance");')

router = "apps/backend/src/plugins/offerings/router.ts"
replace(router, 'import { attendanceService } from "./attendance-service.ts";', 'import { AttendanceSaveConflictError, attendanceService } from "./attendance-service.ts";')
replace(router, '    try {\n      res.json(await attendanceService.save(req.params.id!, parsedDate.data, parsedBody.data, req.user!.id));\n    } catch (err) {\n      handleError(err, res, "Could not save attendance");\n    }', '    // Existing browsers without a server version must fail closed instead of\n    // silently overwriting attendance saved by a different lecturer.\n    if (parsedBody.data.expectedUpdatedAt === undefined) {\n      res.status(428).json({ error: "Reload attendance before saving; the expected server version is missing" });\n      return;\n    }\n    try {\n      res.json(await attendanceService.save(req.params.id!, parsedDate.data, parsedBody.data, req.user!.id));\n    } catch (err) {\n      if (err instanceof AttendanceSaveConflictError) {\n        res.status(409).json({ error: err.message });\n        return;\n      }\n      handleError(err, res, "Could not save attendance");\n    }')

service = "apps/backend/src/plugins/offerings/attendance-service.ts"
replace(service, 'export const attendanceService = {', 'export class AttendanceSaveConflictError extends Error {\n  constructor() {\n    super("Attendance has changed since it was loaded. Reload and review the latest register before saving.");\n    this.name = "AttendanceSaveConflictError";\n  }\n}\n\nexport const attendanceService = {')
replace(service, '      const existingSession = existing[0] ?? null;\n      const historicalRows = existingSession', '      const existingSession = existing[0] ?? null;\n      // Compare inside the same transaction, after locking the session row.\n      // A stale request cannot delete records, alter Check 1 or send alerts.\n      if (input.expectedUpdatedAt !== undefined &&\n          (existingSession?.updatedAt.toISOString() ?? null) !== input.expectedUpdatedAt) {\n        throw new AttendanceSaveConflictError();\n      }\n      const historicalRows = existingSession')
replace(service, 'UPDATE "pms_attendance"."AttendanceSession" SET "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = ${sessionId}', 'UPDATE "pms_attendance"."AttendanceSession"\n          SET "updatedAt" = GREATEST(CURRENT_TIMESTAMP, "updatedAt" + INTERVAL \'1 millisecond\')\n          WHERE "id" = ${sessionId}')

recheck = "apps/backend/src/plugins/offerings/attendance-recheck-service.ts"
replace(recheck, '        SET "updatedAt" = CURRENT_TIMESTAMP\n        WHERE "id" = ${session.id}', '        SET "updatedAt" = GREATEST(CURRENT_TIMESTAMP, "updatedAt" + INTERVAL \'1 millisecond\')\n        WHERE "id" = ${session.id}')

tests = "apps/backend/src/plugins/offerings/attendance-service-db.test.ts"
replace(tests, 'import { attendanceService } from "./attendance-service.ts";', 'import { AttendanceSaveConflictError, attendanceService } from "./attendance-service.ts";')
with Path(tests).open("a", encoding="utf-8") as file:
    file.write('''\n\ndescribeDb("attendance save optimistic concurrency", () => {\n  test("stale versions reject without replacing records, then an updated version succeeds", async () => {\n    const offering = await createOffering("save-version");\n    const student = await createStudent("save-version");\n    await enroll(offering.id, student.id);\n    const date = "2026-09-17";\n    const initial = await attendanceService.get(offering.id, date);\n    expect(initial.updatedAt).toBeNull();\n\n    const first = await attendanceService.save(offering.id, date, {\n      expectedUpdatedAt: initial.updatedAt,\n      records: [{ studentId: student.id, status: "Present", note: "first writer" }],\n    });\n    expect(first.updatedAt).not.toBeNull();\n    const before = await storedRecords(offering.id, date);\n\n    await expect(attendanceService.save(offering.id, date, {\n      expectedUpdatedAt: initial.updatedAt,\n      records: [{ studentId: student.id, status: "Absent", note: "stale writer" }],\n    })).rejects.toBeInstanceOf(AttendanceSaveConflictError);\n    expect(await storedRecords(offering.id, date)).toEqual(before);\n\n    const next = await attendanceService.save(offering.id, date, {\n      expectedUpdatedAt: first.updatedAt,\n      records: [{ studentId: student.id, status: "Late", note: "current writer" }],\n    });\n    expect(next.updatedAt).not.toBe(first.updatedAt);\n    expect(next.records.find((item) => item.studentId === student.id)?.status).toBe("Late");\n  });\n\n  test("two concurrent saves of one version permit exactly one writer", async () => {\n    const offering = await createOffering("concurrent-save");\n    const student = await createStudent("concurrent-save");\n    await enroll(offering.id, student.id);\n    const date = "2026-09-18";\n    const baseline = await attendanceService.save(offering.id, date, {\n      expectedUpdatedAt: null,\n      records: [{ studentId: student.id, status: "Present", note: "original" }],\n    });\n    const results = await Promise.allSettled([\n      attendanceService.save(offering.id, date, {\n        expectedUpdatedAt: baseline.updatedAt,\n        records: [{ studentId: student.id, status: "Absent", note: "first" }],\n      }),\n      attendanceService.save(offering.id, date, {\n        expectedUpdatedAt: baseline.updatedAt,\n        records: [{ studentId: student.id, status: "Late", note: "second" }],\n      }),\n    ]);\n    expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1);\n    const rejected = results.find((result) => result.status === "rejected");\n    expect(rejected?.status).toBe("rejected");\n    if (rejected?.status === "rejected") {\n      expect(rejected.reason).toBeInstanceOf(AttendanceSaveConflictError);\n    }\n    const stored = await storedRecords(offering.id, date);\n    expect(stored).toHaveLength(1);\n    expect(["first", "second"]).toContain(stored[0]?.note);\n  });\n});\n''')

source_tests = "apps/frontend/app/(shell)/attendance/attendance-record-hydration.test.ts"
with Path(source_tests).open("a", encoding="utf-8") as file:
    file.write('''\n\ndescribe("Attendance version-safe save", () => {\n  test("sends the hydrated server version, checks refreshed cache and preserves local marks on conflict", () => {\n    expect(attendanceClientSource).toContain("currentSession.updatedAt !== baselineVersionRef.current");\n    expect(attendanceClientSource).toContain("expectedUpdatedAt: baselineVersionRef.current");\n    expect(attendanceClientSource).toContain("err.status === 409");\n    expect(attendanceClientSource).toContain("if (!saved) return;");\n  });\n});\n''')

Path("packages/shared-types/src/attendance-save-version.test.ts").write_text('''import { describe, expect, test } from "bun:test";\nimport { SaveAttendanceInput } from "./attendance";\n\nconst records = [{ studentId: "11111111-1111-4111-8111-111111111111", status: "Present" }];\n\ndescribe("attendance save version contract", () => {\n  test("accepts null for an unsaved session and an ISO version for an existing one", () => {\n    expect(SaveAttendanceInput.safeParse({ records, expectedUpdatedAt: null }).success).toBe(true);\n    expect(SaveAttendanceInput.safeParse({ records, expectedUpdatedAt: "2026-09-17T07:00:00.000Z" }).success).toBe(true);\n  });\n\n  test("rejects malformed server versions", () => {\n    expect(SaveAttendanceInput.safeParse({ records, expectedUpdatedAt: "yesterday" }).success).toBe(false);\n  });\n});\n''', encoding="utf-8")

# The temporary patch is not part of the completed PR; remove the runner and itself.
Path(".github/workflows/attendance-hardening-once.yml").unlink()
Path("scripts/attendance-hardening-once.py").unlink()
print("Applied optimistic concurrency guard, regression tests, and removed one-shot runner")
